server:
  port: 6001

spring:
  profiles:
    active: dev
  application:
    name: voicecomm-flowable

flowable:
  async-executor-activate: false
  #数据库生成策略
  database-schema-update: false  #每次启动都删除重新创建数据库
  database-schema: flowable
