server:
  port: 6001

spring:
  profiles:
    active: dev
  application:
    name: voicecomm-flowable
flowable:
  async-executor-activate: false
  database-schema-update: false
  #mysql8.0\u9700\u52A0\u4E0A\u5F53\u524D\u914D\u7F6E
  database-schema: flowable
